server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/ecomdb
    username: admin_ecom_user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # or update / none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
