spring:
  application:
    name: discovery-service
  # If discovery service reads its config from the config-server,
  # the client/container should be started with SPRING_CONFIG_IMPORT
  # pointing to the config-server (see run examples below).

server:
  port: 8761

eureka:
  instance:
    hostname: discovery-service

  client:
    # MUST be enabled so ApplicationInfoManager bean is created
    enabled: true

    # keep these false to avoid the server registering with itself
    register-with-eureka: false
    fetch-registry: false

    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.config: DEBUG